module CcImport
  SKIP_SETS = [
    'Apac Land Promos',
    'Euro Land Promos',
    'Guru Land Promos',
    'Token Promos',
    'Unique & Misc. Promos',
    'Collectors Edition',
    'Collectors Edition - International',
    'Anthologies',
    'Coldsnap Theme Deck Reprints',
    'Deckmasters',
    'Japanese Duel Decks: Jace vs Chandra',
    'Commander Oversized Cards',
    'Pre-Release & Release Promos',
    'Alternate 4th Edition',
    '',
    nil,
    'Unique & Misc Promos',
    'Face the Hydra',
    'Battle the Horde',
    'FNM Promos',
    'IDW',
  ]

  SKIP_CARDS = [
    'Poison Counter',
    'Double-Sided Card Checklist',
    'Emblem - Sorin, Lord of Innistrad',
    'Emblem - Koth of the Hammer',
    'Emblem - Venser, the Sojourner',
    'Emblem - Tamiyou, the Moon Sage',
    'Emblem - Liliana of the Dark Realms',
    'Emblem - Domri Rade',
    'Emblem - Elspeth, Knight-Errant',
    "Emblem - Elspeth, Sun's Champion",
    "Emblem - Kiora, the Crashing Wave",
    'Swallow the Hero Whole',
    '',
    nil,
  ]

  SET_LOOKUP = {
    'Alpha'                           => 'Limited Edition Alpha',
    'Beta'                            => 'Limited Edition Beta',
    'Unlimited'                       => 'Unlimited Edition',
    'Sixth Edition'                   => 'Classic Sixth Edition',
    'Ravnica'                         => 'Ravnica: City of Guilds',
    'Timeshifted'                     => 'Time Spiral "Timeshifted"',
    'Battle Royale'                   => 'Battle Royale Box Set',
    'Planechase - Planes'             => 'Planechase',
    'Archenemy Schemes'               => 'Archenemy',
    'Archenemy Singles'               => 'Archenemy',
    'Planechase 2012'                 => 'Planechase 2012 Edition',
    'Planechase 2012 Oversized Cards' => 'Planechase 2012 Edition',
    'Magic 2014'                      => 'Magic 2014 Core Set',
    'Magic 2015'                      => 'Magic 2015 Core Set',
    'Duel Decks: Heroes VS Monsters'  => 'Duel Decks: Heroes vs. Monsters',
    'Commander 2013'                  => 'Commander 2013 Edition',
    'Jace vs Vraska'                  => 'Duel Decks: Jace vs. Vraska',
    'Journey Into Nyx'                => 'Journey into Nyx',
    'Modern Event Deck Singles'       => 'Modern Event Deck 2014',
    'Book Promos'                     => 'Promo set for Gatherer'
  }
end
